apiVersion: v1
kind: ConfigMap
metadata:
  name: gcp-cloud-config
data:
  gcp.conf: |
    [Global]
    project-id = PROJECT_ID_PLACEHOLDER
    regional = true
    region = REGION_PLACEHOLDER
    multizone = true
    node-tags = NODE_TAGS_PLACEHOLDER
    node-instance-prefix = INSTANCE_PREFIX_PLACEHOLDER
    network-name = NETWORK_NAME_PLACEHOLDER
    subnetwork-name = SUBNETWORK_NAME_PLACEHOLDER
    
    [LoadBalancer]
    load-balancer-type = External