apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-node-termination-handler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aws-node-termination-handler
  template:
    metadata:
      labels:
        app: aws-node-termination-handler
    spec:
      automountServiceAccountToken: false
      enableServiceLinks: false
      containers:
      - name: aws-node-termination-handler
        image: aws-node-termination-handler
        imagePullPolicy: IfNotPresent
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: ENABLE_SPOT_INTERRUPTION_DRAINING
          value: "true"
        - name: ENABLE_SCHEDULED_EVENT_DRAINING
          value: "true"
        - name: ENABLE_REBALANCE_MONITORING
          value: "false"
        - name: ENABLE_REBALANCE_DRAINING
          value: "false"
        - name: ENABLE_SQS_TERMINATION_DRAINING
          value: "true"
        - name: AWS_REGION
          value: ""
        - name: QUEUE_URL
          value: ""
        - name: DELETE_SQS_MSG_IF_NODE_NOT_FOUND
          value: "false"
        - name: DRY_RUN
          value: "false"
        - name: CORDON_ONLY
          value: "false"
        - name: TAINT_NODE
          value: "false"
        - name: EXCLUDE_FROM_LOAD_BALANCERS
          value: "false"
        - name: JSON_LOGGING
          value: "false"
        - name: LOG_LEVEL
          value: "info"
        - name: WEBHOOK_URL
          value: ""
        - name: WORKERS
          value: "10"
        - name: METADATA_TRIES
          value: "3"
        - name: KUBERNETES_SERVICE_HOST
          value: ""
        - name: KUBERNETES_SERVICE_PORT
          value: ""
        - name: KUBECONFIG
          value: "/etc/kubernetes/kubeconfig"
        - name: AWS_SHARED_CREDENTIALS_FILE
          value: "/etc/aws/credentials"
        - name: ENABLE_KUBERNETES_EVENTS
          value: "true"
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 128Mi
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: svc-kubeconfig
          mountPath: /etc/kubernetes
        - name: credentials
          mountPath: /etc/aws
      volumes:
      - name: tmp
        emptyDir: {}
      - name: svc-kubeconfig
        secret:
          secretName: service-network-admin-kubeconfig
          defaultMode: 0640
      - name: credentials
        secret:
          secretName: node-management-creds
      nodeSelector:
        kubernetes.io/os: linux
