apiVersion: v1
kind: Service
metadata:
  name: machine-config-server-{{ .VersionURLCompliant }}
spec:
  ports:
  - port: 80
    name: http
    protocol: TCP
    targetPort: 8080
  selector:
    app: machine-config-server-{{ .VersionURLCompliant }}
  type: ClusterIP
